services:
  - type: web
    name: ogspace-1
    env: node
    buildCommand: cd api && npm install && npm run build
    startCommand: cd api && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: ogspace
    env: python
    buildCommand: pip install -r ml/requirements.txt
    startCommand: uvicorn ml.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONPATH
        value: .
