# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavioral_model.proto
# Regenerate with: bash ml/generate_proto.sh
"""
Hand-crafted gRPC stub for behavioral_model.proto.

This file is API-compatible with the grpc_tools.protoc-generated version and
will be replaced by the real generated file when grpc_tools is available.
"""

from __future__ import annotations

import grpc


class BehavioralModelServiceStub:
    """Client stub for BehavioralModelService."""

    def __init__(self, channel: grpc.Channel) -> None:
        self.TrainModel = channel.unary_unary(
            "/mirrormind.BehavioralModelService/TrainModel",
            request_serializer=None,
            response_deserializer=None,
        )
        self.GetModelInfo = channel.unary_unary(
            "/mirrormind.BehavioralModelService/GetModelInfo",
            request_serializer=None,
            response_deserializer=None,
        )


class BehavioralModelServiceServicer:
    """Server-side servicer base class for BehavioralModelService.

    Subclass this and implement TrainModel and GetModelInfo.
    """

    def TrainModel(self, request, context):
        """Train a behavioral model from wallet actions.

        Args:
            request: TrainModelRequest
            context: grpc.ServicerContext

        Returns:
            TrainModelResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Get cached model info for a wallet address.

        Args:
            request: GetModelInfoRequest
            context: grpc.ServicerContext

        Returns:
            GetModelInfoResponse
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


class _BehavioralModelServiceHandler(grpc.GenericRpcHandler):
    """GenericRpcHandler that routes calls to the servicer."""

    def __init__(self, servicer: BehavioralModelServiceServicer) -> None:
        self._servicer = servicer
        self._handlers = {
            "TrainModel": grpc.unary_unary_rpc_method_handler(
                servicer.TrainModel,
                request_deserializer=None,
                response_serializer=None,
            ),
            "GetModelInfo": grpc.unary_unary_rpc_method_handler(
                servicer.GetModelInfo,
                request_deserializer=None,
                response_serializer=None,
            ),
        }

    def service_name(self) -> str:
        return "mirrormind.BehavioralModelService"

    def service(self, handler_call_details):
        method = handler_call_details.method.split("/")[-1]
        return self._handlers.get(method)


def add_BehavioralModelServiceServicer_to_server(
    servicer: BehavioralModelServiceServicer,
    server: grpc.Server,
) -> None:
    """Register the servicer with a gRPC server.

    This is the standard pattern generated by grpc_tools.protoc.
    """
    server.add_generic_rpc_handlers((_BehavioralModelServiceHandler(servicer),))
