# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: behavioral_model.proto
# Regenerate with: bash ml/generate_proto.sh
"""
Hand-crafted protobuf stub for behavioral_model.proto.

This file uses simple Python dataclasses to represent the proto messages.
It is API-compatible with the grpc_tools.protoc-generated version and will
be replaced by the real generated file when grpc_tools is available.
"""

from __future__ import annotations

import struct
from dataclasses import dataclass, field
from typing import List


@dataclass
class WalletAction:
    tx_hash: str = ""
    action_type: str = ""
    protocol: str = ""
    asset_in: str = ""
    asset_out: str = ""
    amount_usd: float = 0.0
    block_timestamp: int = 0
    block_number: int = 0


@dataclass
class ModelDimensions:
    risk_profile: int = 64
    timing_patterns: int = 64
    protocol_preferences: int = 128
    asset_behavior: int = 128
    decision_context: int = 128
    total: int = 512


@dataclass
class TrainModelRequest:
    wallet_address: str = ""
    actions: List[WalletAction] = field(default_factory=list)
    model_version: int = 1


@dataclass
class TrainModelResponse:
    vector: bytes = b""          # 512 float32 values, little-endian
    performance_score: float = 0.0
    model_version: int = 1
    dimensions: ModelDimensions = field(default_factory=ModelDimensions)
    model_id: str = ""


@dataclass
class GetModelInfoRequest:
    wallet_address: str = ""


@dataclass
class GetModelInfoResponse:
    wallet_address: str = ""
    model_version: int = 0
    performance_score: float = 0.0
    dimensions: ModelDimensions = field(default_factory=ModelDimensions)
    trained_at: int = 0
